eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
security:
  user:
    name: admin
    password: 123456
  basic:
    enable: false
server:
  port: 9006
logging:
  file: "logs/boot-admin.log"
spring:
  application:
    name: admin-service
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      turbine:
        clusters: default
        location: turbine-service
